services:
  gateway:
    build: ./gateway
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5000
      CONFIG_FILE: config.yaml
      # CHANGE THIS #
      JWT_KEY: f0a26ed99c8033ea873a8d4dab66d2c406771ea023b26fdc72cbe94b9b962761
      JWT_ALG: HS256
      LOG_FILE: gateway.log
      LOG_FORMAT: "%(asctime)s -- [%(funcName)s] %(message)s"
      LOG_LEVEL: DEBUG
    volumes:
      - ./gateway:/app/
    command: python main.py
    ports:
      - 8000:5000
    depends_on:
      - profiles

  profiles:
    build: ./profiles
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      LOG_FILE: profiles.log
      LOG_FORMAT: "%(asctime)s -- [%(funcName)s] %(message)s"
      LOG_LEVEL: DEBUG
    volumes:
      - ./profiles:/app/
    command: uvicorn main:app --host 0.0.0.0 --port 5000

volumes:
  gateway:
  profiles: