services:
  gateway:
    build: ./gateway
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./gateway:/app/
    command: python main.py
    ports:
      - 8001:5000
    depends_on:
      - profiles

  profiles:
    build: ./profiles
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./profiles:/app/
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload

volumes:
  gateway:
  profiles: