services:

  gateway:
    build: ./gateway
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5000
      CONFIG_FILE: config.yaml
      # CHANGE THIS #
      JWT_KEY: f0a26ed99c8033ea873a8d4dab66d2c406771ea023b26fdc72cbe94b9b962761
      JWT_ALG: HS256
      LOG_FILE: gateway.log
      LOG_FORMAT: "%(asctime)s -- [%(funcName)s] %(message)s"
      LOG_LEVEL: DEBUG
    volumes:
      - ./gateway:/app/
    command: python main.py
    ports:
      - 8000:5000
    depends_on:
      - profiles
      - auth

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # DEV ONLY
      PGADMIN_DEFAULT_PASSWORD: example # DEV ONLY
    ports:
      - 5050:80
    depends_on:
      - auth-db

  auth-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example # DEV ONLY
      POSTGRES_PASSWORD: example # DEV ONLY
    ports:
      - 5432

  profiles:
    build: ./profiles
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      LOG_FILE: profiles.log
      LOG_FORMAT: "%(asctime)s -- [%(funcName)s] %(message)s"
      LOG_LEVEL: DEBUG
    volumes:
      - ./profiles:/app/
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    depends_on:
      - auth

  auth:
    build: ./auth
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      DB_URL: postgresql+psycopg2://example:example@auth-db:5432/postgres
      LOG_FILE: auth.log
      LOG_FORMAT: "%(asctime)s -- [%(funcName)s] %(message)s"
      LOG_LEVEL: DEBUG
    volumes:
      - ./auth:/app/
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    depends_on:
      - auth-db

volumes:
  gateway:
  auth:
  profiles: