services:
  gateway:
    build: ./gateway
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      LOG_FILE: gateway.log
      LOG_FORMAT: "%(asctime)s -- [%(funcName)s] %(message)s"
      LOG_LEVEL: 10 # DEBUG LEVEL
    volumes:
      - ./gateway:/app/
    command: python main.py
    ports:
      - 8001:5000
    depends_on:
      - profiles

  profiles:
    build: ./profiles
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      LOG_FILE: profiles.log
      LOG_FORMAT: "%(asctime)s -- [%(funcName)s] %(message)s"
      LOG_LEVEL: 10 # DEBUG LEVEL
    volumes:
      - ./profiles:/app/
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload

volumes:
  gateway:
  profiles: