"""empty message

Revision ID: 11b5835dbcf0
Revises: d7024709ca10
Create Date: 2022-06-16 06:52:20.935242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b5835dbcf0'
down_revision = 'd7024709ca10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
