"""empty message

Revision ID: 837fb34a28ff
Revises: 322ea42a8ad3
Create Date: 2022-06-11 05:43:20.309877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837fb34a28ff'
down_revision = '322ea42a8ad3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    # ### end Alembic commands ###
